apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  containers:
    - name: frontend
      image: 922057391995.dkr.ecr.us-east-1.amazonaws.com/cart:2.0.0
  initContainers:
    - name: aws-ssm-param-store
      image: 922057391995.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-param-store:2.0.0
      args: ["sample:dev.docdb.pass"]
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080